### ISSUE TITLE
'This browser doesn't support WebRTC'

### ISSUE THREAD

**Issue by aj-Interest** [gjovanov/facer#13]
Hi Goran Jovanov,

the code is working perfectly on local but how can i access this app on another machine on the same network in browser ?, i tried by replacing localhost with machine name but post that on camera page it shows message 'This browser doesn't support WebRTC'
![Capture](https://user-images.githubusercontent.com/47139678/73831244-ffc33c00-482b-11ea-846f-3c0012cc05f0.JPG)

**Comment by amitsjedhe** [comment]
https://facer.xplorify.net/ this work perfectly  how can i make like this ?

**Comment by gjovanov** [comment]
Hi @aj-Interest ,
if your app is listening only on `localhost:3000` then you can't access it from another machine which is on the same network.

You can start the app (`/server/index.js`) e.g. on all IP addresses `0.0.0.0` and then in that case your app will be available on localhost as well as on the local IP or by Machine name (from another machine in the same network).

You can set the ENV Variable HOST=0.0.0.0 for that purpose.

Then you all these should be working:
1. `localhost:3000`
2. `local_ip_address:3000`
3. `machine_name:3000`

Hope it helps.


/GJ

**Comment by gjovanov** [comment]
@aj-Interest did you manage to achieve accessibility from another machine?

**Comment by aj-Interest** [comment]
yes, with below code now i am able to access it over https from another machine on same network and it's working fine

var express = require('express')
var fs = require('fs')
var https = require('https')
var app = express()

app.get('/', function (req, res) {
  res.send('hello world')
})

https.createServer({
  key: fs.readFileSync('server.key'),
  cert: fs.readFileSync('server.cert')
}, app)
.listen(3000, function () {
  console.log('Example app listening on port 3000! Go to https://machine-name:3000/')
})

**Comment by aj-Interest** [comment]
Yes, with below piece of code it's working for me

var express = require('express')
var fs = require('fs')
var https = require('https')
var app = express()

app.use(nuxt.render)
  
https.createServer({
  key: fs.readFileSync('server.key'),
  cert: fs.readFileSync('server.cert')
}, app)
.listen(3000, function () {
  console.log('Example app listening on port 3000! Go to https://machine-name:3000/')
})

**Comment by gjovanov** [comment]
Ok tnx for confirming @aj-Interest. Closing then, feel free open a new one in case you find something else.
